services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
  
  app:
    image: ${IMAGE_NAME:-ghcr.io/bibektimilsina00/egfilm:latest}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      NEXT_PUBLIC_TMDB_API_KEY: ${TMDB_API_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1

volumes:
  postgres_data:
