export const FALLBACK_VIDEO_PROVIDERS = [
    {
        id: 'fallback-vidsrc-icu',
        name: 'VidSrc ICU',
        slug: 'vidsrc-icu',
        quality: '1080p',
        isEnabled: true,
        isDefault: true,
        sortOrder: 0,
        movieTemplate: 'https://vidsrc.icu/embed/movie/{tmdbId}',
        tvTemplate: 'https://vidsrc.icu/embed/tv/{tmdbId}/{season}/{episode}',
        supportsImdb: true,
        supportsTmdb: true,
        hasMultiQuality: true,
        hasSubtitles: true,
        hasAutoplay: false,
        description: 'BEST - Clean interface with minimal ads, supports movies, TV shows, anime and manga',
        logoUrl: null
    },
    {
        id: 'fallback-vidsrc-cc',
        name: 'VidSrc.cc',
        slug: 'vidsrc-cc',
        quality: '1080p',
        isEnabled: true,
        isDefault: false,
        sortOrder: 1,
        movieTemplate: 'https://vidsrc.cc/v2/embed/movie/{tmdbId}',
        tvTemplate: 'https://vidsrc.cc/v2/embed/tv/{tmdbId}/{season}/{episode}',
        supportsImdb: false,
        supportsTmdb: true,
        hasMultiQuality: true,
        hasSubtitles: true,
        hasAutoplay: false,
        description: 'V2 player with custom subtitles, player events and minimal ads',
        logoUrl: null
    },
    {
        id: 'fallback-vidlink-pro',
        name: 'VidLink Pro',
        slug: 'vidlink-pro',
        quality: '1080p',
        isEnabled: true,
        isDefault: false,
        sortOrder: 2,
        movieTemplate: 'https://vidlink.pro/movie/{tmdbId}',
        tvTemplate: 'https://vidlink.pro/tv/{tmdbId}/{season}/{episode}',
        supportsImdb: false,
        supportsTmdb: true,
        hasMultiQuality: true,
        hasSubtitles: true,
        hasAutoplay: false,
        description: 'Biggest library: 51K+ movies and 36K+ shows from 13+ sources with minimal ads',
        logoUrl: null
    },
    {
        id: 'fallback-vidsrc-to',
        name: 'VidSrc.to',
        slug: 'vidsrc-to',
        quality: '1080p',
        isEnabled: true,
        isDefault: false,
        sortOrder: 3,
        movieTemplate: 'https://vidsrc.to/embed/movie/{tmdbId}',
        tvTemplate: 'https://vidsrc.to/embed/tv/{tmdbId}/{season}/{episode}',
        supportsImdb: true,
        supportsTmdb: true,
        hasMultiQuality: true,
        hasSubtitles: true,
        hasAutoplay: false,
        description: 'Next-gen API with auto-update links and minimal ads',
        logoUrl: null
    },
    {
        id: 'fallback-vidsrc-net',
        name: 'VidSrc.net',
        slug: 'vidsrc-net',
        quality: '1080p',
        isEnabled: true,
        isDefault: false,
        sortOrder: 4,
        movieTemplate: 'https://vidsrc.net/embed/movie/{tmdbId}',
        tvTemplate: 'https://vidsrc.net/embed/tv/{tmdbId}/{season}/{episode}',
        supportsImdb: true,
        supportsTmdb: true,
        hasMultiQuality: true,
        hasSubtitles: true,
        hasAutoplay: false,
        description: 'Official VidSrc mirror with reliable uptime and minimal ads',
        logoUrl: null
    }
];
